import { Poliza } from "./types";

// Helper to generate dates relative to today for realistic demo data
function formatDate(date: Date): string {
    const day = String(date.getDate()).padStart(2, "0");
    const month = String(date.getMonth() + 1).padStart(2, "0");
    const year = date.getFullYear();
    return `${day}/${month}/${year}`;
}

function daysFromNow(days: number): string {
    const d = new Date();
    d.setDate(d.getDate() + days);
    return formatDate(d);
}

export const mockPolizas: Poliza[] = [
    {
        ESTADO: "VIGENTE",
        TELEFONO: "+5492614001234",
        CODIGO: "POL-001",
        FECHA: "15/01/2025",
        ASEGURADO: "Juan Carlos Méndez",
        COMPAÑIA: "Sancor Seguros",
        POLIZA: "AU-2025-00142",
        COBERTURA: "Todo Riesgo con Franquicia",
        VENCIMIENTO: daysFromNow(5),
        REFERENCIAS: "Renovación automática",
        COSTO_MENSUAL: 45000,
        OBSERVACION: "Cliente preferencial",
    },
    {
        ESTADO: "IMPAGA",
        TELEFONO: "+5492614005678",
        CODIGO: "POL-002",
        FECHA: "20/02/2025",
        ASEGURADO: "María Laura Fernández",
        COMPAÑIA: "La Segunda",
        POLIZA: "HO-2025-00087",
        COBERTURA: "Hogar Integral",
        VENCIMIENTO: daysFromNow(12),
        REFERENCIAS: "2 cuotas pendientes",
        COSTO_MENSUAL: 28500,
        OBSERVACION: "Contactar urgente",
    },
    {
        ESTADO: "VIGENTE",
        TELEFONO: "+5492614009012",
        CODIGO: "POL-003",
        FECHA: "10/03/2025",
        ASEGURADO: "Roberto Alejandro Gutiérrez",
        COMPAÑIA: "Federación Patronal",
        POLIZA: "VI-2025-00215",
        COBERTURA: "Vida Obligatorio",
        VENCIMIENTO: daysFromNow(18),
        REFERENCIAS: "",
        COSTO_MENSUAL: 15200,
        OBSERVACION: "",
    },
    {
        ESTADO: "A RENOVAR",
        TELEFONO: "+5492614003456",
        CODIGO: "POL-004",
        FECHA: "05/11/2024",
        ASEGURADO: "Ana Beatriz Romero",
        COMPAÑIA: "Sancor Seguros",
        POLIZA: "AU-2024-00098",
        COBERTURA: "Terceros Completo",
        VENCIMIENTO: daysFromNow(3),
        REFERENCIAS: "Quiere cambiar cobertura",
        COSTO_MENSUAL: 32000,
        OBSERVACION: "Llamar antes de renovar",
    },
    {
        ESTADO: "VIGENTE",
        TELEFONO: "+5492614007890",
        CODIGO: "POL-005",
        FECHA: "18/06/2025",
        ASEGURADO: "Carlos Eduardo Peralta",
        COMPAÑIA: "Zurich",
        POLIZA: "AU-2025-00301",
        COBERTURA: "Todo Riesgo sin Franquicia",
        VENCIMIENTO: daysFromNow(45),
        REFERENCIAS: "",
        COSTO_MENSUAL: 62000,
        OBSERVACION: "Vehículo 0km",
    },
    {
        ESTADO: "IMPAGA",
        TELEFONO: "+5492614002345",
        CODIGO: "POL-006",
        FECHA: "22/04/2025",
        ASEGURADO: "Lucía Valentina Torres",
        COMPAÑIA: "Mapfre",
        POLIZA: "HO-2025-00154",
        COBERTURA: "Combinado Familiar",
        VENCIMIENTO: daysFromNow(8),
        REFERENCIAS: "1 cuota pendiente",
        COSTO_MENSUAL: 19800,
        OBSERVACION: "",
    },
    {
        ESTADO: "VIGENTE",
        TELEFONO: "+5492614006789",
        CODIGO: "POL-007",
        FECHA: "30/05/2025",
        ASEGURADO: "Martín Ignacio Sosa",
        COMPAÑIA: "La Segunda",
        POLIZA: "AU-2025-00267",
        COBERTURA: "Terceros Completo",
        VENCIMIENTO: daysFromNow(25),
        REFERENCIAS: "",
        COSTO_MENSUAL: 27500,
        OBSERVACION: "Bonificación por antigüedad",
    },
    {
        ESTADO: "VIGENTE",
        TELEFONO: "+5492614004321",
        CODIGO: "POL-008",
        FECHA: "12/07/2025",
        ASEGURADO: "Florencia Aylen Castro",
        COMPAÑIA: "Federación Patronal",
        POLIZA: "VI-2025-00189",
        COBERTURA: "Vida Individual",
        VENCIMIENTO: daysFromNow(60),
        REFERENCIAS: "",
        COSTO_MENSUAL: 12400,
        OBSERVACION: "",
    },
    {
        ESTADO: "IMPAGA",
        TELEFONO: "+5492614008765",
        CODIGO: "POL-009",
        FECHA: "08/08/2025",
        ASEGURADO: "Diego Armando Ríos",
        COMPAÑIA: "Sancor Seguros",
        POLIZA: "AU-2025-00312",
        COBERTURA: "Todo Riesgo con Franquicia",
        VENCIMIENTO: daysFromNow(15),
        REFERENCIAS: "3 cuotas pendientes",
        COSTO_MENSUAL: 38900,
        OBSERVACION: "Riesgo de baja",
    },
    {
        ESTADO: "VIGENTE",
        TELEFONO: "+5492614001098",
        CODIGO: "POL-010",
        FECHA: "25/09/2025",
        ASEGURADO: "Valentina Sol Herrera",
        COMPAÑIA: "Zurich",
        POLIZA: "HO-2025-00201",
        COBERTURA: "Hogar Premium",
        VENCIMIENTO: daysFromNow(90),
        REFERENCIAS: "",
        COSTO_MENSUAL: 35600,
        OBSERVACION: "Cobertura extendida",
    },
    {
        ESTADO: "A RENOVAR",
        TELEFONO: "+5492614005432",
        CODIGO: "POL-011",
        FECHA: "14/10/2024",
        ASEGURADO: "Fernando Nicolás Vega",
        COMPAÑIA: "Mapfre",
        POLIZA: "AU-2024-00445",
        COBERTURA: "Todo Riesgo con Franquicia",
        VENCIMIENTO: daysFromNow(10),
        REFERENCIAS: "Interesado en ampliar cobertura",
        COSTO_MENSUAL: 41200,
        OBSERVACION: "Buen pagador",
    },
    {
        ESTADO: "VIGENTE",
        TELEFONO: "+5492614009876",
        CODIGO: "POL-012",
        FECHA: "03/11/2025",
        ASEGURADO: "Camila Rocío Domínguez",
        COMPAÑIA: "La Segunda",
        POLIZA: "VI-2025-00278",
        COBERTURA: "Vida Obligatorio",
        VENCIMIENTO: daysFromNow(120),
        REFERENCIAS: "",
        COSTO_MENSUAL: 14800,
        OBSERVACION: "",
    },
    {
        ESTADO: "VIGENTE",
        TELEFONO: "+5492614003210",
        CODIGO: "POL-013",
        FECHA: "19/12/2025",
        ASEGURADO: "Sebastián Matías López",
        COMPAÑIA: "Federación Patronal",
        POLIZA: "AU-2025-00389",
        COBERTURA: "Terceros Completo",
        VENCIMIENTO: daysFromNow(22),
        REFERENCIAS: "",
        COSTO_MENSUAL: 29300,
        OBSERVACION: "",
    },
    {
        ESTADO: "IMPAGA",
        TELEFONO: "+5492614007654",
        CODIGO: "POL-014",
        FECHA: "27/01/2026",
        ASEGURADO: "Paula Andrea Molina",
        COMPAÑIA: "Zurich",
        POLIZA: "HO-2026-00023",
        COBERTURA: "Hogar Integral",
        VENCIMIENTO: daysFromNow(28),
        REFERENCIAS: "1 cuota pendiente",
        COSTO_MENSUAL: 22100,
        OBSERVACION: "Primer aviso enviado",
    },
    {
        ESTADO: "VIGENTE",
        TELEFONO: "+5492614002109",
        CODIGO: "POL-015",
        FECHA: "08/02/2026",
        ASEGURADO: "Tomás Agustín Navarro",
        COMPAÑIA: "Sancor Seguros",
        POLIZA: "AU-2026-00056",
        COBERTURA: "Todo Riesgo sin Franquicia",
        VENCIMIENTO: daysFromNow(150),
        REFERENCIAS: "",
        COSTO_MENSUAL: 55000,
        OBSERVACION: "Plan corporativo",
    },
];
